name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Update Username from Secrets
        env:
          API_RPPS_URL: ${{ secrets.API_RPPS_URL }}
        run: echo API_KEY="$API_KEY" > ./local.properties

      - name: Run tests
        run: |
          ./gradlew test