name: Run Tests

on:
  push:
    branches:
      - actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: chmod +x ./gradlew


  test-api:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Update API_URL from Secrets
        env:
          API_RPPS_URL: ${{ secrets.API_RPPS_URL }}
        run: echo "apiRppsUrl=${{ env.API_RPPS_URL }}" > ./local.properties

      - name: Run tests
        run: |
          ./gradlew test

  test-db:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Run tests
        run: |
          ./gradlew test
